[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
glide = "4.16.0"
gson = "2.10.1"
# cardstackview = "2.3.4"  # TODO: 스와이프 기능 구현 시 주석 해제
recyclerview = "1.3.2"
cardview = "1.0.0"
maps = "18.2.0"
places = "3.3.0"
location = "21.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
# cardstackview = { group = "com.github.yuyakaido", name = "card-stack-view", version.ref = "cardstackview" }  # TODO: 스와이프 기능 구현 시 주석 해제
# cardstackview = { group = "com.yuyakaido.android", name = "card-stack-view", version.ref = "cardstackview" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
google-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "maps" }
google-places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
google-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "location" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

